#!/bin/bash

if [ -z $KARABO ]
then
    echo "Please activate Karabo (type \". activate\" in your karabo directory)"
    exit 1
fi

if [ "$1" = "-h" -o "$1" = "--help" ]
then
	cat <<-END
		$0 - show logs in an xterm

		  $0 [-h|--help] device-server*

		This shows the logs of all given device servers in a xterm.
		This only works if logging is enabled for that device server.
		If no device server is given, the logs of all device servers
		are shown in their xterms.
	END
fi

cd $KARABO/var/services

for service in ${@:-*}
do
    if [ -x $service/log/run ]
    then
        xterm -T "$service" -e tail -F "$service/log/current" &
    fi
done
