#!/bin/bash

#check the existDb docker image
IMAGE=europeanxfel/existdb:2.2
CONTAINER=karabo_existdb

#check if the image is already available
docker images $IMAGE --format "{{.Repository}}:{{.Tag}}" | grep $IMAGE > /dev/null
if [[ $? -ne 0 ]]; then
    # pull in case we miss this image
    docker pull $IMAGE 
    if [[ $? -ne 0 ]]; then
        echo "ERROR: is docker installed?"
        exit 1
    fi
fi

mkdir -p $KARABO/var/data/exist_data
# unfortunately ps --filter ancestor=$IMAGE would always return 0
docker ps --all --filter name=$CONTAINER | grep $CONTAINER > /dev/null
# if no contaneir from the image is running, start it.
if [[ $? -ne 0 ]]; then
    docker run -d -p 8080:8080 -v $KARABO/var/data/exist_data:/opt/exist_data/export/ --name $CONTAINER $IMAGE > /dev/null
else
    docker start $CONTAINER > /dev/null
fi

echo "------------------------------------------"

if [[ $? -eq 0 ]]; then
    echo "Configuration DB was started."
    echo "You can access the backend at: http://localhost:8080/exist/"
else
    echo "Error Starting the Configuration DB"
    exit 1
fi