#!/bin/bash

if [ -z $KARABO ]
then
    echo "Please activate Karabo (type \". activate\" in your Karabo directory)"
    exit 1
fi

if [ "$1" = "-h" -o "$1" = "--help" ]
then
	cat <<-END
	$0 - stop Karabo device servers

	  $0 [-h|--help] device-server*

	stops the given device servers. If no device server is given, all
	device servers are stopped. Nothing happens for an already stopped
	device server.
	END
fi

. karabo-supervise

exec svc -d ${@:-*}
