#!/bin/bash
echo "Stopping eXist database"

#check the existDb docker image
IMAGE=europeanxfel/existdb:2.2
CONTAINER=karabo_existdb
mkdir -p $KARABO/var/data/exist_data

docker ps --filter name=$CONTAINER | grep $CONTAINER > /dev/null
if [[ $? -eq 0 ]]; then
    docker container kill $CONTAINER > /dev/null
fi

# Force a clean returncode
exit 0
