#!/bin/bash

if [ -z $KARABO ]
then
    echo "Please activate Karabo (type \". activate\" in your Karabo directory)"
    exit 1
fi

if [ "$1" = "-h" -o "$1" = "--help" ]
then
	cat <<-END
		$0 - start Karabo device servers

		  $0 [-h|--help] device-servers*

		start given device servers. If none is given, start all.

		If the device server is already running, nothing happens.
	END
fi

. karabo-supervise

exec svc -u ${@:-*}
