#!/bin/bash

if [ -z $KARABO ]
then
    echo "Please activate Karabo (type \". activate\" in your Karabo directory)"
    exit 1
fi

cd $KARABO/var/services

shopt -s nullglob

if ! svok $KARABO/services
then
    # do not magically start all devices
    for service in *
    do
        touch $service/down
    done
    echo starting supervise
    supervise $KARABO/services &
    sleep 1  # give it some time to actually start
fi
