#! /bin/bash
#######################################################################
# karabo-restart restarts those START applications which have died
# author: CY 16.1.2013

# Make sure Karabo is installed
if [ -z $KARABO ]; then
  echo
  echo "\$KARABO is not defined. Make sure you have sourced the activate script for the Karabo Framework which you would like to use."
  exit 1
fi

# Make sure the script runs in $KARABO/var/config
scriptDir=$KARABO/var/config
cd ${scriptDir}
if [ $? -ne 0 ]; then
    echo "ERROR Could not change directory to ${scriptDir}"
    exit 1;
fi

foo=".config"
if [ ! -e $foo ]; then
    echo "ERROR no previous karabo-start"
    exit 1
fi

arg=$(grep "args:" $foo | grep "karabo-start" | grep -v grep | awk '{print $3}')
if [ -n "$arg" ]; then
    echo "INFO Restarting with argument: $arg"
fi 

export RESTART="yes"
karabo-start $arg

exit $?

