#!/bin/bash
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
echo "Stopping influxDB container"

#check the  docker image
IMAGE=influxdb:1.7.8
CONTAINER=karabo_influxdb

docker ps --filter name=$CONTAINER | grep $CONTAINER > /dev/null
if [[ $? -eq 0 ]]; then
    docker container kill $CONTAINER > /dev/null
fi

# Force a clean returncode
exit 0
