#!/bin/bash
# This file is part of Karabo.
#
# http://www.karabo.eu
#
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
#
# Karabo is free software: you can redistribute it and/or modify it under
# the terms of the MPL-2 Mozilla Public License.
#
# You should have received a copy of the MPL-2 Public License along with
# Karabo. If not, see <https://www.mozilla.org/en-US/MPL/2.0/>.
#
# Karabo is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
cd $(dirname $0)
if [ -z $KARABO ]; then
    echo "\$KARABO is not defined. Make sure you have sourced the activate script for the Karabo Framework which you would like to use."
    exit 1
fi

_term() {
    $KARABO/extern/bin/imq stop
}
# Stop Broker on sigterm

trap _term SIGTERM SIGINT

$KARABO/extern/bin/imq start
sleep 1
PID=`ps -ef | grep -w imqbrokerd | grep -v grep | awk '{print $2}'`
echo $PID

# the imq tool will start the broker but not as a child of this shell
# for this reason we have to resort to poll the PID
while [ -e /proc/$PID ]
do
    sleep .6
done
