#!/bin/bash
# This file is part of Karabo.
#
# http://www.karabo.eu
#
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
#
# Karabo is free software: you can redistribute it and/or modify it under
# the terms of the MPL-2 Mozilla Public License.
#
# You should have received a copy of the MPL-2 Public License along with
# Karabo. If not, see <https://www.mozilla.org/en-US/MPL/2.0/>.
#
# Karabo is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
echo "Stopping influxDB container"

#check the  docker image
IMAGE=influxdb:1.7.8
CONTAINER=karabo_influxdb

docker ps --filter name=$CONTAINER | grep $CONTAINER > /dev/null
if [[ $? -eq 0 ]]; then
    docker container kill $CONTAINER > /dev/null
fi

# Force a clean returncode
exit 0
