#!/bin/bash

SCRIPT=$(basename $0)
DEFAULT_DEFAULT=exfl-broker:7777
if [ -z $KARABO_BROKER ]; then
    BROKER_DEFAULT=$DEFAULT_DEFAULT
else
    # KARABO_BROKER is set, but might contain more than one URI.
    # So just use the first one, i.e. everything before the first ',':
    BROKER_DEFAULT=$(cut -d ',' -f 1 <<< "$KARABO_BROKER")
    # Then strip off the leading 'tcp://' to have e.g. exflbkr02n0.desy.de:7777:
    BROKER_DEFAULT=${BROKER_DEFAULT#tcp://}
fi

if [ ${#@} -le 0 ] || [ $1 == "-h" ] || [ $1 == "--help" ]; then
    # print help message if first argument asks for help
    echo
    echo "$SCRIPT - Look into messages stuck on broker:"
    echo 
    echo "  $SCRIPT [-h|--help] topic [broker:port [firstMessageIdx [numMessages]]]"
    echo
    echo "Default broker:port is taken as first item in \$KARABO_BROKER if that is"
    echo "defined and is $DEFAULT_DEFAULT otherwise."
    echo "Needs karabo-querybroker as dependency."
    echo
    exit 0
fi

TOPIC=$1
# Broker from argument or from default if argument not set (or null).
BROKER=${2:-$BROKER_DEFAULT}

COMMAND="karabo-querybroker -b $BROKER list msg -t t -n $TOPIC -nocheck"
# If more arguments are given, use them (otherwise ${3:+<...>} stays empty):
COMMAND="$COMMAND ${3:+-startMsgIndex $3} ${4:+-maxMsgsRet $4}"

# Command gives something like:
# ...
#-----------------------------------------------------------------------------------
#Message #   Message IDs                                     Priority   Body Type
#-----------------------------------------------------------------------------------
#0           ID:15-192.168.140.159-59611-1459519722221       4          BytesMessage
#1           ID:8-192.168.140.159-59620-1459519722615        4          BytesMessage
# ...

declare -i counter=0

for msgID in `$COMMAND | grep 'ID:' | awk '{print $2}' `; do
    echo "message query no. ${counter}: "
    karabo-querybroker -b $BROKER query msg -t t -n $TOPIC -nocheck -msgID $msgID
    echo
    echo "=================================================================="
    echo
    counter+=1
done
