#!/bin/bash
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
cd $(dirname $0)
if [ -z $KARABO ]; then
    echo "\$KARABO is not defined. Make sure you have sourced the activate script for the Karabo Framework which you would like to use."
    exit 1
fi

$KARABO/extern/bin/imq stop $@
