exclude: |
  (?x)(
      ^build/|
      ^extern/|
      ^doc/|
      ^src/service.in/|
      ^src/environment.in/|
      ^ci/
  )

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: destroyed-symlinks
      - id: check-symlinks

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: ["-style=file"]
        files: |
          (?x)(
              ^src/karabo/|
              ^src/karathon/|
              ^src/integrationTests/|
              ^src/brokerMessageLogger/|
              ^src/cppLongTests/|
              ^src/templates/cpp/|
              ^src/deviceServer/
          )

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      -  id: isort
         name: isort pythonKarabo
         files: |
          (?x)(
              ^src/pythonKarabo/
          )
      -  id: isort
         name: isort pythonGui
         files: |
          (?x)(
              ^src/pythonGui/
          )

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: |
          (?x)(
              ^conda-recipes/|
              ^src/pythonKarabo/karabo/integration_tests/|
              ^src/pythonKarabo/karabo/bound_api/tests/
          )

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.4.0
      hooks:
      -   id: pyupgrade
          args: [--py37-plus]
