exclude: |
  (?x)(
      ^build/|
      ^extern/|
      ^doc/|
      ^public_docs/|
      ^src/service.in/|
      ^src/environment.in/|
      ^src/karabind/stubs|
      ^ci/
  )

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: check-xml
      - id: pretty-format-json
        args: [ --autofix ]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.2
    hooks:
      - id: clang-format
        entry: |
          bash -c '
          if [ -n "${CI_JOB_ID}" ]; then
            clang-format --Werror -i -style=file --dry-run "$@"
          else
            clang-format --Werror -i -style=file "$@"
          fi
          '
        files: |
          (?x)(
              ^src/karabo/|
              ^src/karabind/|
              ^src/integrationTests/|
              ^src/brokerMessageLogger/|
              ^src/cppLongTests/|
              ^src/templates/cpp/|
              ^src/deviceServer/
          )

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort pythonKarabo
        files: |
          (?x)(
              ^src/pythonKarabo/
          )
      - id: isort
        name: isort pythonGui
        files: |
          (?x)(
              ^src/pythonGui/
          )

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [ --py311-plus ]
