# .readthedocs.yaml

# This file is part of Karabo.
#
# http://www.karabo.eu
#
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
#
# Karabo is free software: you can redistribute it and/or modify it under
# the terms of the MPL-2 Mozilla Public License.
#
# You should have received a copy of the MPL-2 Public License along with
# Karabo. If not, see <https://www.mozilla.org/en-US/MPL/2.0/>.
#
# Karabo is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.

# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
   os: ubuntu-22.04
   tools:
      python: "3.12"
   apt_packages:
      - doxide
   jobs:
     pre_install:
       - pip install mkdocs-material mkdocs-section-index mkdocs-literate-nav 
       - pip install mkdocstrings-python

# we only build the public documentation
mkdocs:
   configuration: mkdocs.yml
