.test_build_template: &test_build
  script:
    - export REL_OS_NAME=$(lsb_release -is)
    - export REL_OS_VERS_LONG=$(lsb_release -rs | sed -r "s/^([0-9]+).*/\1/")
    - export BUILD_TYPE=Debug
    - export KARABO_BROKER_TOPIC="gitlab_ci_$CI_JOB_ID"
    - curl http://exflserv05.desy.de/karabo/karaboFramework/tags/$KARABO_TAG/karabo-$KARABO_TAG-Release-$REL_OS_NAME-$REL_OS_VERS_LONG-x86_64.sh > karabo.sh
    - bash karabo.sh --prefix=/root
    - source /root/karabo/activate
    - pushd $CI_PROJECT_DIR
    - export GTEST_OUTPUT=xml:$CI_PROJECT_DIR/report.xml
    - make test
  artifacts:
    when: always
    reports:
      junit:
        - report.xml
    paths:
      - report.xml
    expire_in: 1 week

##### Test build #####
test:centos7:
  image: europeanxfel/karabo-ci:centos-7gcc7
  before_script:
    - source /opt/rh/devtoolset-7/enable
    - export KARABO_TAG="latest_build"
  <<: *test_build

test:centos7latest:
  image: europeanxfel/karabo-ci:centos-7gcc7
  before_script:
    - source /opt/rh/devtoolset-7/enable
    - export KARABO_TAG="latest_prerelease_build"
  <<: *test_build

# add more operating systems if necessary
