exclude: |
  (?x)(
      ^doc/
  )

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: check-xml
      - id: pretty-format-json
        args: [ --autofix ]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.0
    hooks:
      - id: clang-format
        args: [ "-style=file" ]
        files: |
          (?x)(
              ^src/
          )
