#!/bin/bash
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
# This file is part of the initial configuration of Karabo
cd $KARABO/var/data
exec envdir $KARABO/var/environment karabo-cppserver serverId=karabo/guiServer 'serverId=karabo/guiServer' 'deviceClasses=GuiServerDevice' 'autoStart[0]={GuiServerDevice.port=44444}' 'visibility=4' 'Logger.priority=INFO' 2>&1
