from karabo.common.scenemodel.api import (
    BitfieldModel, CheckBoxModel, ChoiceElementModel, ComboBoxModel,
    DigitIconsModel, DirectoryModel, DisplayAlignedImageModel,
    DisplayCommandModel, DisplayIconsetModel, DisplayImageElementModel,
    DisplayImageModel, DisplayLabelModel, DisplayPlotModel,
    DisplayStateColorModel, DoubleLineEditModel, EditableListElementModel,
    EditableListModel, EditableSpinBoxModel, EvaluatorModel, FileInModel,
    FileOutModel, FloatSpinBoxModel, HexadecimalModel, IntLineEditModel,
    KnobModel, LineEditModel, LinePlotModel, MonitorModel, ScientificImageModel,
    SelectionIconsModel, SingleBitModel, SliderModel, TableElementModel,
    TextIconsModel, VacuumWidgetModel, WebcamImageModel, XYPlotModel
)

WIDGET_FACTORIES = {
    'Bitfield': BitfieldModel,
    'DisplayCheckBox': CheckBoxModel,
    'EditableCheckBox': CheckBoxModel,
    'DisplayChoiceElement': ChoiceElementModel,
    'EditableChoiceElement': ChoiceElementModel,
    'DisplayComboBox': ComboBoxModel,
    'EditableComboBox': ComboBoxModel,
    'DisplayCommand': DisplayCommandModel,
    'DisplayDirectory': DirectoryModel,
    'EditableDirectory': DirectoryModel,
    'DisplayFileIn': FileInModel,
    'EditableFileIn': FileInModel,
    'DisplayFileOut': FileOutModel,
    'EditableFileOut': FileOutModel,
    'DisplayIconset': DisplayIconsetModel,
    'DisplayAlignedImage': DisplayAlignedImageModel,
    'DisplayImage': DisplayImageModel,
    'DisplayImageElement': DisplayImageElementModel,
    'ScientificImageDisplay': ScientificImageModel,
    'WebcamImageDisplay': WebcamImageModel,
    'DisplayLabel': DisplayLabelModel,
    'DisplayLineEdit': LineEditModel,
    'EditableLineEdit': LineEditModel,
    'EditableList': EditableListModel,
    'EditableListElement': EditableListElementModel,
    'DisplayPlot': DisplayPlotModel,
    'EditableSpinBox': EditableSpinBoxModel,
    'Hexadecimal': HexadecimalModel,
    'DoubleLineEdit': DoubleLineEditModel,
    'IntLineEdit': IntLineEditModel,
    'Slider': SliderModel,
    'Knob': KnobModel,
    'XYPlot': XYPlotModel,
    'XYVector': LinePlotModel,
    'DisplayTrendline': LinePlotModel,
    'FloatSpinBox': FloatSpinBoxModel,
    'DisplayStateColor': DisplayStateColorModel,
    'DisplayTableElement': TableElementModel,
    'EditableTableElement': TableElementModel,
    'Evaluator': EvaluatorModel,
    'TextIcons': TextIconsModel,
    'DigitIcons': DigitIconsModel,
    'SelectionIcons': SelectionIconsModel,
    'Monitor': MonitorModel,
    'SingleBit': SingleBitModel,
    'CryoCoolerWidget': VacuumWidgetModel,
    'HydraulicValveWidget': VacuumWidgetModel,
    'MaxiGaugeWidget': VacuumWidgetModel,
    'MembranePumpWidget': VacuumWidgetModel,
    'MotorWidget': VacuumWidgetModel,
    'PressureGaugeWidget': VacuumWidgetModel,
    'PressureSwitchWidget': VacuumWidgetModel,
    'RightAngleValveWidget': VacuumWidgetModel,
    'ShutOffValveWidget': VacuumWidgetModel,
    'TemperatureProbeWidget': VacuumWidgetModel,
    'TurboPumpWidget': VacuumWidgetModel,
    'ValveWidget': VacuumWidgetModel,
    'AgilentIonWidget': VacuumWidgetModel,
    'LampWidget': VacuumWidgetModel,
}
