from karabo_gui.scenemodel.api import (
    BitfieldModel, CheckBoxModel, ChoiceElementModel, ComboBoxModel,
    DirectoryModel, DisplayAlignedImageModel, DisplayCommandModel,
    DisplayIconsetModel, DisplayImageModel, DisplayImageElementModel,
    DisplayLabelModel, DisplayPlotModel, DisplayStateColorModel,
    DoubleLineEditModel, EditableListModel, EditableListElementModel,
    EditableSpinBoxModel, EvaluatorModel, FileInModel, FileOutModel,
    FloatSpinBoxModel, HexadecimalModel, DigitIconsModel,
    SelectionIconsModel, TextIconsModel, IntLineEditModel, KnobModel,
    LineEditModel, LinePlotModel, MonitorModel, SingleBitModel,
    SliderModel, TableElementModel, VacuumWidgetModel, XYPlotModel
)

WIDGET_FACTORIES = {
    'DisplayAlignedImage': DisplayAlignedImageModel,
    'Bitfield': BitfieldModel,
    'DisplayCheckBox': CheckBoxModel,
    'EditableCheckBox': CheckBoxModel,
    'DisplayChoiceElement': ChoiceElementModel,
    'EditableChoiceElement': ChoiceElementModel,
    'DisplayComboBox': ComboBoxModel,
    'EditableComboBox': ComboBoxModel,
    'DisplayCommand': DisplayCommandModel,
    'DisplayDirectory': DirectoryModel,
    'EditableDirectory': DirectoryModel,
    'DisplayFileIn': FileInModel,
    'EditableFileIn': FileInModel,
    'DisplayFileOut': FileOutModel,
    'EditableFileOut': FileOutModel,
    'DisplayIconset': DisplayIconsetModel,
    'DisplayImage': DisplayImageModel,
    'DisplayImageElement': DisplayImageElementModel,
    'DisplayLabel': DisplayLabelModel,
    'DisplayLineEdit': LineEditModel,
    'EditableLineEdit': LineEditModel,
    'EditableList': EditableListModel,
    'EditableListElement': EditableListElementModel,
    'DisplayPlot': DisplayPlotModel,
    'EditableSpinBox': EditableSpinBoxModel,
    'Hexadecimal': HexadecimalModel,
    'DoubleLineEdit': DoubleLineEditModel,
    'IntLineEdit': IntLineEditModel,
    'Slider': SliderModel,
    'Knob': KnobModel,
    'XYPlot': XYPlotModel,
    'XYVector': LinePlotModel,
    'DisplayTrendline': LinePlotModel,
    'FloatSpinBox': FloatSpinBoxModel,
    'DisplayStateColor': DisplayStateColorModel,
    'DisplayTableElement': TableElementModel,
    'EditableTableElement': TableElementModel,
    'Evaluator': EvaluatorModel,
    'TextIcons': TextIconsModel,
    'DigitIcons': DigitIconsModel,
    'SelectionIcons': SelectionIconsModel,
    'Monitor': MonitorModel,
    'SingleBit': SingleBitModel,
    'CryoCoolerWidget': VacuumWidgetModel,
    'HydraulicValveWidget': VacuumWidgetModel,
    'MaxiGaugeWidget': VacuumWidgetModel,
    'MembranePumpWidget': VacuumWidgetModel,
    'MotorWidget': VacuumWidgetModel,
    'PressureGaugeWidget': VacuumWidgetModel,
    'PressureSwitchWidget': VacuumWidgetModel,
    'RightAngleValveWidget': VacuumWidgetModel,
    'ShutOffValveWidget': VacuumWidgetModel,
    'TemperatureProbeWidget': VacuumWidgetModel,
    'TurboPumpWidget': VacuumWidgetModel,
    'ValveWidget': VacuumWidgetModel,
}
