#!/bin/bash
cd $(dirname $0)
if [ -z $KARABO ]; then
  echo "\$KARABO is not defined. Make sure you have sourced the activate script for the Karabo Framework which you would like to use."
  exit 1
fi

if [ -z $@ ]; then
    $KARABO/bin/karabo-deviceserver DeviceServer
else
    $KARABO/bin/karabo-deviceserver "$@"
fi


