#!/bin/bash
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#

# Returns true if the first version argument is less than the second version argument
__version_lt() { test "$(echo "$@" | tr " " "\n" | sort -rV | head -n 1)" != "$1"; }

__lint_clang_format() {
    # Put all staged files that conform to C++ source filename suffixes and
    # that are not Deleted or Renamed into the collection of files to be
    # checked for formatting.
    SRC_FILES=($(git diff --cached --name-only --diff-filter=dr | grep -e "\.cc\'" -e "\.cpp\'"  -e "\.hh\'" -e "\.h\'" -e "\.hpp\'"))
    local -i num_files=${#SRC_FILES[@]}
    if [[ $num_files -eq 0 ]]; then
        return 0  # no file to be checked
    fi
    echo "clang-format version in use: `clang-format --version`"
    echo ""

    local -i ok_files=0
    local -i err_files=0
    local file_check_code
    for SRC_FILE in "${SRC_FILES[@]}"; do
        eval "clang-format -n -i --Werror $SRC_FILE"
        file_check_code=$?
        if [[ $file_check_code != 0 ]]; then
            ((err_files+=1))
        else
            echo "--- OK for format of '$SRC_FILE'"
            ((ok_files+=1))
        fi
    done
    if [[ $err_files -gt 0 ]]; then
        echo "--- $err_files file(s) (out of $((err_files+ok_files))) failed verification for formatting compliance."
        return $err_files
    else
        echo "--- $ok_files file(s) successfully verified for formatting compliance."
        return 0
    fi
}

# Performs linting of the staged C++ files in the Framework repository.

# Checks if clang-format is available and its version matches the CI (13.0.0)
CI_CLANG_FORMAT_VERSION="13.0.0"
CLANG_FORMAT_VERSION=$(clang-format --version | grep -P '\d+\.\d+\.\d+' -o)
ret_code=$?
if [[ $ret_code != 0 ]]; then
    echo ""
    echo "WARNING: pre-commit C++ format linting SKIPPED."
    echo "         Reason: clang-format not available. Please install clang-format version $CI_CLANG_FORMAT_VERSION."
    echo ""
    exit 0
fi
if __version_lt $CLANG_FORMAT_VERSION $CI_CLANG_FORMAT_VERSION; then
    echo ""
    echo "WARNING: pre-commit C++ format linting SKIPPED."
    echo "         Reason: Local clang-format version, $CLANG_FORMAT_VERSION, is older than the CI's, $CI_CLANG_FORMAT_VERSION."
    echo ""
    exit 0
fi

__lint_clang_format
retval=$?
if [[ retval -eq 0 ]]; then
    exit 0
else
    echo ""
    echo "COMMIT ABORTED."
    echo ""
    exit 1
fi
