#!/bin/bash

# helper script for running the test manually.

find ../.. -name "*.gcda" -delete
../../auto_build_all.sh CodeCoverage --runTests
../../auto_build_all.sh CodeCoverage --runIntegrationTests
