#!/bin/bash

# helper scritp for running the test manually.

get_abs_path() {
	echo `cd "$1"; pwd`
}

BASE_PATH=$(get_abs_path "../..")

find $BASE_PATH/build/coverage/karabo/build -name "*.gcda" -delete

rm -rf $BASE_PATH/build/coverage/karabo/DeviceClient_Test
rm -rf $BASE_PATH/build/coverage/karabo/karaboHistory

testDir=$BASE_PATH/build/coverage/karabo

rm -rf $testDir/testresults/

( cd $testDir && make CONF=CodeCoverage -j1 test )
