# This file is part of Karabo.
#
# http://www.karabo.eu
#
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
#
# Karabo is free software: you can redistribute it and/or modify it under
# the terms of the MPL-2 Mozilla Public License.
#
# You should have received a copy of the MPL-2 Public License along with
# Karabo. If not, see <https://www.mozilla.org/en-US/MPL/2.0/>.
#
# Karabo is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
{% set xfel_conda_channel = os.environ.get('XFEL_CONDA_CHANNEL', 'exflctrl01.desy.de') %}
{% set conda_local_channel = os.environ.get('CONDA_LOCAL_CHANNEL_ENV', '') %}
name: karabogui

channels:
  - http://{{ xfel_conda_channel }}/karabo/channel
  - http://{{ xfel_conda_channel }}/karabo/channel/mirror/conda-forge
  - conda-forge
{{ conda_local_channel }}

# Group the dependencies by '# +++ <group name>' so that they are grouped accordingly in
# the meta.yaml file
dependencies:
    # +++ build
  - python=3.14.*
  - setuptools>=69.*
  - setuptools_scm>=7.*
  - pip>=23.3.*
  # +++ run
  - python=3.14.*
  - flake8=7.3.0
  - isort=8.0.1
  - pytest=9.0.2
  - pytest-qt=4.5.0
  - pytest-cov=7.1.0
  - pytest-mock=3.15.1
  - pytest-subtests=0.15.0
  - pytest-xdist=3.8.*
  # GUI
  - qtpy=2.4.3
  - pyqtgraph=0.14.0
  - pyqt6=6.11.0
  - qscintilla2=2.14.1
  # Plotting and utils
  - numpy=2.4.3
  - scipy=1.17.1
  - lttbc=0.3.0
  - natsort=8.4.0
  # Other
  - tabulate=0.10.0
  - traits=7.1.0
  - requests=2.33.1
  - python-dateutil=2.9.0
  - pyyaml=6.0.3
  - pint=0.25.3


environment:
  PYTHONPATH:
    - {{ root }}
  KARABO_GUI_ROOT:
    - {{ root }}
  OMP_NUM_THREADS: 1
  QT_API: "pyqt6"
