KARABO_ALARM_SERVICE = "Karabo_AlarmService"
KARABO_CONFIG_MANAGER = "KaraboConfigurationManager"
KARABO_DAEMON_MANAGER = "KaraboDaemonManager"
KARABO_PROJECT_MANAGER = "KaraboProjectManager"

CORE_DEVICES_NAMES = (
    KARABO_ALARM_SERVICE,
    KARABO_CONFIG_MANAGER,
    KARABO_DAEMON_MANAGER,
    KARABO_PROJECT_MANAGER
)
