CHANNEL_DIAMETER = 5
CHANNEL_HEIGHT = 10
CHANNEL_WIDTH = 20
CHANNEL_INPUT = 'InputChannel'
CHANNEL_OUTPUT = 'OutputChannel'
CONNECTION_OFFSET = CHANNEL_WIDTH - CHANNEL_DIAMETER / 2
DATA_DIST_COPY = 'copy'
DATA_DIST_SHARED = 'shared'
