#!/bin/bash
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
# This file is part of the initial configuration of Karabo
cd $KARABO/var/data
CONFIG_DB=karaboDB
exec envdir $KARABO/var/environment karabo-middlelayerserver serverId=karabo/configServer 'deviceClasses=ConfigurationManager' init='{"KaraboConfigurationManager":{"classId":"ConfigurationManager", "dbName": "'$CONFIG_DB'"}}' 'visibility=4' 2>&1
