#!/usr/bin/env bash

__enable_gcc7() {
    # for the Centos7 build
    DIST_MAJOR=$(echo $LSB_RELEASE_VERSION | sed -r "s/^([0-9]+).*/\1/")
    if [[ $1 = "CentOS" && $DIST_MAJOR = "7" ]]; then
        source /opt/rh/devtoolset-7/enable
    fi
}

__lang_setting() {
    case "$1" in
        CentOS|AlmaLinux|RedHat)
            localedef -c -i en_US -f UTF-8 en_US.utf8
            export LANG=en_US.UTF-8
            __enable_gcc7 $1
            ;;
        Ubuntu)
            locale-gen en_US.UTF-8
            update-locale LANG=en_US.UTF-8
            ;;
        Debian)
            export DEBIAN_FRONTEND=noninteractive
            echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
            locale-gen
            ;;
        *) echo "unknown target os for lang_setting: $1" ;;
    esac
}


XVFB=/usr/bin/Xvfb
XVFB_DISP=:99.0
XVFB_ARGS="$XVFB_DISP -screen 0 1024x768x24 -ac"

__start_Xvfb() {
    case "$1" in
        CentOS|AlmaLinux)
            export DISPLAY=$XVFB_DISP
            $XVFB $XVFB_ARGS &
            ;;
        Ubuntu|Debian)
            export DISPLAY=$XVFB_DISP
            start-stop-daemon --start -b -x $XVFB -- $XVFB_ARGS
            ;;
        *) echo "unknown target os for xvfb: $1" ;;
    esac
}

echo "Start to prepare environment for job: {$1}"

REL_OS_NAME=$LSB_RELEASE_DIST
__lang_setting $REL_OS_NAME

if [ "${KARABO_UPLOAD_HOST}" == "" ]; then
    export KARABO_UPLOAD_HOST=xkarabo@exflctrl01
fi
if [ "${KARABO_UPLOAD_DIR}" == "" ]; then
    export KARABO_UPLOAD_DIR=/var/www/html/karabo
fi
if [ "${KARABO_UPLOAD_CURL_PREFIX}" == "" ]; then
    export KARABO_UPLOAD_CURL_PREFIX=http://exflctrl01.desy.de/karabo
fi


export SSH_PREFIX=$KARABO_UPLOAD_HOST:$KARABO_UPLOAD_DIR
export LATEST_RELEASE_TAG=latest_build
export LATEST_PRERELEASE_TAG=latest_prerelease_build
export NIGHTLY_TAG=Nightly

export KARABO_BROKER_TOPIC="gitlab_ci_$CI_JOB_ID"
export KARABO_PROJECT_DB=existdbhost
export KARABO_PROJECT_DB_PORT=8080
export KARABO_TEST_PROJECT_DB=existdbhost
export KARABO_TEST_PROJECT_DB_PORT=8080
export KARABO_TEST_INFLUXDB_HOST=influxdbhost
export KARABO_TEST_INFLUXDB_PORT=8086
export KARABO_TEST_INFLUXDB_DB=$INFLUXDB_DB

export KARABO_INFLUXDB_DBNAME=$INFLUXDB_DB
# this is for the influxDb /query and /ping endpoint
export KARABO_INFLUXDB_QUERY_USER=$INFLUXDB_USER
export KARABO_INFLUXDB_QUERY_PASSWORD=$INFLUXDB_USER_PASSWORD
export KARABO_INFLUXDB_QUERY_URL=tcp://$KARABO_TEST_INFLUXDB_HOST:$KARABO_TEST_INFLUXDB_PORT
# this is for the influxDb /write endpoint
export KARABO_INFLUXDB_WRITE_USER=$INFLUXDB_ADMIN_USER
export KARABO_INFLUXDB_WRITE_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
export KARABO_INFLUXDB_WRITE_URL=tcp://$KARABO_TEST_INFLUXDB_HOST:$KARABO_TEST_INFLUXDB_PORT

# todo refactor
export KARABO_TEST_INFLUXDB_USER=$INFLUXDB_USER
export KARABO_TEST_INFLUXDB_PASSWORD=$INFLUXDB_USER_PASSWORD
export KARABO_TEST_INFLUXDB_ADMUSER=$INFLUXDB_ADMIN_USER
export KARABO_TEST_INFLUXDB_ADMUSER_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
