#!/usr/bin/env bash

__cpp_unit_tests() {
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runTests --skipPythonTests
}

__python_unit_tests() {
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runTests --skipCppTests
}

__cpp_integration_tests() {
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runIntegrationTests --skipPythonTests
}

__python_integration_tests() {
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runIntegrationTests --skipCppTests
}

__cpp_deps_build_tests() {
    export FORCED_DEPS_TAG=$CI_COMMIT_REF_SLUG
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runTests --runIntegrationTests --skipPythonTests
}

__python_deps_build_tests() {
    export FORCED_DEPS_TAG=$CI_COMMIT_REF_SLUG
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runTests --runIntegrationTests --skipCppTests
}

__long_tests() {
    if [[ "$CI_PIPELINE_SOURCE" == "schedule" && "$SCHEDULED_JOB" != "long-tests" ]]; then
        # another scheduled job was triggered
        echo "Not a 'long-tests' job. Skipping."
        exit 0
    fi
    bash ./auto_build_all.sh Debug --numJobs $NUM_COMPILE_JOBS --runLongTests --quiet
}

__coverage_tests() {
    if [[ "$CI_PIPELINE_SOURCE" == "schedule" && "$SCHEDULED_JOB" != "coverage-tests" ]]; then
        # another scheduled job was triggered
        echo "Not a 'coverage-tests' job. Skipping."
        exit 0
    fi
    bash ./auto_build_all.sh CodeCoverage --numJobs $NUM_COMPILE_JOBS --quiet
}

echo "Start to testing job: {$1}"

JOB_SCOPE=$(echo $1 | cut -f1 -d' ')
JOB_TYPE=$(echo $1 | cut -f2 -d' ')
JOB_TYPE=${JOB_TYPE//:}
TARGET_OS=$(echo $1 | cut -f3 -d' ')
TARGET_OS=${TARGET_OS//[}
TARGET_OS=${TARGET_OS//]}

export KARABO_CI_TEST_PLATFORM=$TARGET_OS
export KARABO_BROKER_TOPIC="gitlab_ci_$CI_JOB_ID"
export KARABO_PROJECT_DB=existdb_host
export KARABO_PROJECT_DB_PORT=8080
export KARABO_TEST_PROJECT_DB=existdb_host
export KARABO_TEST_PROJECT_DB_PORT=8080
export KARABO_TEST_INFLUXDB_HOST=influxdb_host
export KARABO_TEST_INFLUXDB_PORT=8086
export KARABO_TEST_INFLUXDB_DB=$INFLUXDB_DB

export KARABO_INFLUXDB_DBNAME=$INFLUXDB_DB
# this is for the influxDb /query and /ping endpoint
export KARABO_INFLUXDB_QUERY_USER=$INFLUXDB_USER
export KARABO_INFLUXDB_QUERY_PASSWORD=$INFLUXDB_USER_PASSWORD
export KARABO_INFLUXDB_QUERY_URL=tcp://$KARABO_TEST_INFLUXDB_HOST:$KARABO_TEST_INFLUXDB_PORT
# this is for the influxDb /write endpoint
export KARABO_INFLUXDB_WRITE_USER=$INFLUXDB_ADMIN_USER
export KARABO_INFLUXDB_WRITE_PASSWORD=$INFLUXDB_ADMIN_PASSWORD
export KARABO_INFLUXDB_WRITE_URL=tcp://$KARABO_TEST_INFLUXDB_HOST:$KARABO_TEST_INFLUXDB_PORT

# todo refactor
export KARABO_TEST_INFLUXDB_USER=$INFLUXDB_USER
export KARABO_TEST_INFLUXDB_PASSWORD=$INFLUXDB_USER_PASSWORD
export KARABO_TEST_INFLUXDB_ADMUSER=$INFLUXDB_ADMIN_USER
export KARABO_TEST_INFLUXDB_ADMUSER_PASSWORD=$INFLUXDB_ADMIN_PASSWORD

if [ "$TARGET_OS" = "miniconda-cmake" ]; then
    __cmake_tests
else
    case "$JOB_SCOPE" in
        python_unit) __python_unit_tests ;;
        cpp_unit) __cpp_unit_tests ;;
        python_integration) __python_integration_tests ;;
        cpp_integration) __cpp_integration_tests ;;
        python_deps) __python_deps_build_tests ;;
        cpp_deps) __cpp_deps_build_tests ;;
        long) __long_tests ;;
        coverage) __coverage_tests ;;
        *)
            echo "unknown job scope: $JOB_SCOPE"
            exit 1
            ;;
    esac
fi
