{% set xfel_conda_channel = os.environ.get('XFEL_CONDA_CHANNEL', 'exflserv05.desy.de') %}
{% set conda_local_channel = os.environ.get('CONDA_LOCAL_CHANNEL_ENV', '') %}
name: karabo-mdl

channels:
  - http://{{ xfel_conda_channel }}/karabo/channel
  - http://{{ xfel_conda_channel }}/karabo/channel/mirror/conda-forge
  - conda-forge
  - defaults
{{ conda_local_channel }}

dependencies:
  - python=3.6.* # [linux]
  # for tests and building
  - flake8
  - pytest=6.1.1
  - setuptools
  - setuptools_scm
  # NATIVE
  - traits=6.0.0
  - python-dateutil
  - lxml
  - numpy<=1.15
  - pint<=0.7
  # MIDDLELAYER
  - openmqc
  - ipython
  # Other
  - conda
environment:
  PYTHONPATH:
    - {{ root }}
