#!/bin/bash

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
. $SCRIPT_DIR/conf

rm -f $FILE_BASE_IT
rm -f $FILE_BASE_UT
rm -f $FILE_BASE

$LCOV_BASE/lcov --capture --initial --no-external --directory $UT_BASE --output-file $FILE_BASE_UT
$LCOV_BASE/lcov --capture --initial --no-external --directory $IT_BASE --output-file $FILE_BASE_IT
$LCOV_BASE/lcov -a $FILE_BASE_UT -a $FILE_BASE_IT -o $FILE_BASE
