#!/bin/bash

. ./conf

SCRIPT_BASE=$(get_abs_path $( dirname "${BASH_SOURCE[0]}" ))

DEST_DIR=`date +%F_%H%M`
DEST_DIR=$SCRIPT_BASE"/"$DEST_DIR"_ut"

if [ ! -d "$DEST_DIR" ]; then
	mkdir $DEST_DIR
fi
cp /home/osboxes/karabo/build/netbeans/karabo/testresults/* $DEST_DIR/
grep "<Failures>" $DEST_DIR/*


