#!/bin/bash
# Copyright (C) European XFEL GmbH Schenefeld. All rights reserved.
# This file is part of the initial configuration of Karabo
cd $KARABO/var/data

# a file-based backend for the project manager can be chosen by using the lines below:
exec envdir $KARABO/var/environment karabo-middlelayerserver serverId=karabo/projectDBServer 'deviceClasses=ProjectManager' \
init='{"KaraboProjectDB":{"classId":"ProjectManager", "projectDB":{"protocol": "file_db", "file_db":{"dir": "projectDB"}}}}' 'visibility=4' 2>&1
